version:                         '3'

services:

    apache:
        build:                   ./build/server/
        volumes:
            - ./logs/apache2_access.log:/var/log/apache2/access. log
            - ./logs/apache2_error.log:/var/log/apache2/error.log
            - ./../app:/var/www/html
        ports:
            - "80:80"
